# Generated by Django 5.1.4 on 2025-04-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seat_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.SmallIntegerField(),
        ),
    ]
